# Generated by Django 4.1.5 on 2023-01-30 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DietaryRestriction',
            fields=[
                ('dietary_restriction_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(default='Description of the Dietary Restriction', max_length=500, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('ingredient_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('recipe_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(default='Description of the Recipe', max_length=500, verbose_name='description')),
                ('image', models.CharField(max_length=150)),
                ('dietary_restrictions', models.ManyToManyField(blank=True, to='db.dietaryrestriction')),
                ('ingredients', models.ManyToManyField(related_name='recipes', to='db.ingredient')),
            ],
        ),
    ]
